# Generated by Django 4.1 on 2022-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof', models.CharField(max_length=300)),
                ('descrip', models.TextField()),
                ('who', models.CharField(max_length=200)),
            ],
        ),
    ]
